# Getting Experimental Metadata from DANDI for textures
It can be helpful to view general information about the experimental sessions that produced your data. Since typically each NWB File represents one session, a dandiset's files can be examined to get an overview of each of the sessions. This can vary, depending on who produced the NWB file. In this notebook, NWB Files within one of the Allen Institute's datasets are opened and some basic information is used to make a table of the experimental sessions and their properties.

To clearly identify the sessions for the texture project we need to pull additional metadata entries

### Environment Setup
⚠️**Note: If running on a new environment, run this cell once and then restart the kernel**⚠️

In [1]:
import warnings
warnings.filterwarnings('ignore')

try:
    from databook_utils.dandi_utils import dandi_stream_open
except:
    !git clone https://github.com/AllenInstitute/openscope_databook.git
    %cd openscope_databook
    %pip install -e .

In [1]:
import os

import h5py
import pandas as pd
import remfile

from dandi import dandiapi
from pynwb import NWBHDF5IO

%matplotlib inline

### Getting Dandiset Metadata
To view other data, change `dandiset_id` to be the id of the dandiset you're interested in. If the dandiset is embargoed, set `dandi_api_key` to your DANDI API key.

In [2]:
dandiset_id = "001461"
dandi_api_key = os.environ["DANDI_API_KEY"]

In [3]:
my_dandiset = dandiapi.DandiAPIClient(token=dandi_api_key).get_dandiset(dandiset_id)
print(f"Got dandiset {my_dandiset}")

Got dandiset DANDI:001461/draft

### Get NWB Info
Below are two definitions of thefunction `get_nwb_info`. These function are tailored to our NWB Files; Our *Ophys* and our *Ecephys* datasets respectively. It retrieves a series of important metadata values from the NWB file object. It is likely that the code for accessing the fields of interest to you will be slightly different for your files. This can easily be altered to extract any other information from an NWB file you want as long as you're familiar with the internal layout of your files. However, make sure to change the `columns` field in the pandas dataframe below to properly reflect any changes to the function. `nwb_type` can be set below to 'ephys' or 'ophys' depending on the type of the NWBs of interest.

In [4]:
nwb_type = "ophys" # or, "ephys"

In [7]:
# get experimental information from within ophys file
# getattr is used because not all nwb files have all properties. If not handled like this, errors will arise
def get_ophys_nwb_info(nwb):
        session_time = getattr(nwb, "session_start_time", None)

        metadata_obj = getattr(nwb, "lab_meta_data", {})
        metadata = metadata_obj.get("metadata", None)
        session_id = getattr(metadata, "ophys_session_id", None)
        experiment_id = getattr(metadata, "ophys_experiment_id", None)

        fov_height = getattr(metadata, "field_of_view_height", None)
        fov_width = getattr(metadata, "field_of_view_width", None)
        imaging_depth = getattr(metadata, "imaging_depth", None)
        group = getattr(metadata, "imaging_plane_group", None)
        group_count = getattr(metadata, "imaging_plane_group_count", None)
        container_id = getattr(metadata, "experiment_container_id", None)
        
        subject = getattr(nwb, "subject", None)
        specimen_name = getattr(subject, "subject_id", None)
        age = getattr(subject, "age", None)
        sex = getattr(subject, "sex", None)
        genotype = getattr(subject, "genotype", None)
        
        try: n_rois = nwb.processing["ophys"]["dff"].roi_response_series["traces"].data.shape[1]
        except: n_rois = None
        try: location = list(nwb.imaging_planes.values())[0].location
        except: location = None
        
        intervals = getattr(nwb, "intervals", {})
        if "behavior_presentations" in intervals:
            if intervals["behavior_presentations"][0].image_set[0] == "OpenScope-Texture_stage-A2.5_240404":
                stim_types = "active_single_exemplar"
            elif intervals["behavior_presentations"][0].image_set[0] == "OpenScope-Texture_ShiftedImages_TriangleDistribution_8_13_stage-B2.5_241016":
                stim_types = "active_shifting_exemplars"
            else:
                stim_types = "active_unknown"
                print(f"Unknown session type on: {nwb.session_id}") 
        elif "fam-0-smp-0.tiff_presentations" in intervals:
            stim_types = "passive"  
        else:
            stim_types = "unknown"
            print(f"Unknown session type on: {nwb.session_id}")
        
        stim_tables = [intervals[table_name] for table_name in intervals]
        # gets highest value among final "stop times" of all stim tables in intervals
        session_end = max([table.stop_time[-1] for table in stim_tables if len(table) > 1])

        return [session_time, specimen_name, session_id, experiment_id, container_id, group, group_count, imaging_depth, location, fov_height, fov_width, specimen_name, sex, age, genotype, stim_types, n_rois, session_end]

In [7]:
# get experimental information from within ecephys file
# getattr is used because not all nwb files have all properties. If not handled like this, errors will arise
def get_ephys_nwb_info(nwb):
        session_time = getattr(nwb, "session_start_time", None)

        subject = getattr(nwb, "subject", None)
        specimen_name = getattr(subject, "specimen_name", None)
        age = getattr(subject, "age_in_days", None)
        sex = getattr(subject, "sex", None)
        genotype = getattr(subject, "genotype", None)

        probes = set(getattr(nwb, "devices", {}).keys())
        units = getattr(nwb, "units", [])
        n_units = len(units) if hasattr(units, '__len__') else 0        
        
        intervals = getattr(nwb, "intervals", {})
        stim_types = set(intervals.keys())
        stim_tables = [intervals[table_name] for table_name in intervals]
        # gets highest value among final "stop times" of all stim tables in intervals
        session_end = max([table.stop_time[-1] for table in stim_tables if len(table) > 1])

        return [session_time, specimen_name, sex, age, genotype, probes, stim_types, n_units, session_end]

### Getting Table
Here, each relevant file in the dandiset is streamed and opened remotely to get the information of interest using the function `get_nwb_info`, defined above, and then it is added to a table of sessions and their metadata. Since some files are for specific probes rather than entire sessions, they are skipped.

In [8]:
nwb_table = []
# skip files that aren't main session files
files = [asset for asset in my_dandiset.get_assets() if "probe" not in asset.path]
# swap this with line above for one of our ophys dandisets
# files = [asset for asset in my_dandiset.get_assets() if "raw" not in asset.path]
n_files = len(files)
print(f"{n_files} files retrieved")

extract_nwb_info = get_ephys_nwb_info if nwb_type == "ephys" else get_ophys_nwb_info

for i, file in enumerate(files):
    print(f"Examining file {i+1}/{n_files}: {file.identifier}")    
    # get basic file metadata
    row = [file.identifier, file.size, file.path]
    
    base_url = file.client.session.head(file.base_download_url)
    file_url = base_url.headers["Location"]

    # open and read nwb file with streaming
    rem_file = remfile.File(file_url)
    h5py_file = h5py.File(rem_file, "r")
    io = NWBHDF5IO(file=h5py_file, mode="r", load_namespaces=True)
    nwb = io.read()

    # extract experimental info from within file
    row += extract_nwb_info(nwb)
    nwb_table.append(row)
    del nwb

    # don't run full loop if running in test environment
    if os.environ.get("TESTING", False):
        break

144 files retrieved
Examining file 1/144: 3a99f387-2af0-4ead-9af2-b3fb6319e966
Examining file 2/144: 7c7f7ac5-3252-42c2-8172-db7d8cea3a4b
Examining file 3/144: 6d082069-8960-4bf2-9bec-2c0e0d6c9d5f
Examining file 4/144: 004043f9-321e-445e-b695-85e04002f2f1
Examining file 5/144: 9db56b96-0a4a-4bb3-be7e-2fced9efd393
Examining file 6/144: cdfcd9d0-2de5-46b4-805f-a3f91dfee8b7
Examining file 7/144: 8f2de772-089e-4c2f-bdad-87600da96bb4
Examining file 8/144: 4068057d-9d2d-4f58-a105-7b1e5285504e
Examining file 9/144: c809ff72-2074-4c6e-bf91-a447261b81de
Examining file 10/144: e8a5b4fd-d88a-4b39-80c3-48399374b77e
Examining file 11/144: 1eed7d79-ffc5-4139-8736-48159a72dfc8
Examining file 12/144: ec8ec2f3-c09f-4e38-9bde-10137752c33e
Examining file 13/144: c5d4942c-7f9e-4287-b36a-4ee420e375b7
Examining file 14/144: 6d8ee037-671b-4d9a-82dd-18a5cb80f931
Examining file 15/144: e0523d3c-46bc-45a8-b1d2-8475ec2d5eb8
Examining file 16/144: 5b52d1c0-df79-4a91-a068-cbfaec589f6b
Examining file 17/144: 970a6370-1c76-4397-bea3-891b6f072c8a
Examining file 18/144: 3a4b7fe8-238f-4ee4-8d0f-7adf9920c171
Examining file 19/144: 9f54b3c1-8977-4a8d-9730-15427c1b9e98
Examining file 20/144: b2e21eeb-1399-4040-90c0-4d5bcd42af19
Examining file 21/144: 67eb445a-253d-4b9c-a3e1-3620db56a2b4
Examining file 22/144: 6442325b-7a8b-4a9e-9236-624d7eeabe5e
Examining file 23/144: cb28809f-8dd9-4c68-9357-056b5eaa1c15
Examining file 24/144: 6b9c4eb7-628f-449c-9036-c0aa250d93ca
Examining file 25/144: b6c5184f-3117-41a8-8c30-e1b1d5f59484
Examining file 26/144: cb81ec76-9f8a-4451-a97e-ba1eddbaffa4
Examining file 27/144: c8ce6607-4b95-4809-bcda-6bcf37eded7f
Examining file 28/144: d1d278eb-321f-41b0-bc08-cf77b682ea8b
Examining file 29/144: 699bb3cc-3e43-447f-a91d-4f440d56ff13
Examining file 30/144: 02901995-4d73-458e-b8e4-f5e0cfca4fab
Examining file 31/144: 4b8c8141-ed5f-4e1a-be63-baa92c04d7ff
Examining file 32/144: 5b8ec59e-277f-43e6-bfff-8388abb348d3
Examining file 33/144: b9c60e76-4a64-4bcd-935c-082ca729dc3b
Examining file 34/144: 6ac44346-38b3-4b95-9cf3-204033c268e4
Examining file 35/144: a41b9cc5-8059-433e-abd1-b02dac2c5758
Examining file 36/144: 5c07c0bf-a3e1-480c-ad50-b6ee94c0981c
Examining file 37/144: 7279b2be-1703-4f1a-a01f-b6c43361ba39
Examining file 38/144: 08724566-f89a-45e8-8d1e-5ac4fdf299ee
Examining file 39/144: d41d576c-e551-4ca6-8297-bc49f004cf48
Examining file 40/144: bb8a4d6e-f40b-48a9-b9c6-7b679b169e52
Examining file 41/144: 984e482a-2b07-4004-9d17-04d22bf96687
Examining file 42/144: f1ce147b-c033-4f1d-bd12-78bba28e68fb
Examining file 43/144: 6cc6c965-5633-4c94-a166-061d5fb94391
Examining file 44/144: b422c589-cf6a-493e-aa87-ebec2df75c15
Examining file 45/144: 889e8587-4f32-40aa-8de5-175d7d98f358
Examining file 46/144: 670a7a30-0946-460e-ba10-a83267d9b36d
Examining file 47/144: 32e46125-c9ea-4ec4-8528-bf96db023c85
Examining file 48/144: d81eee92-91ee-474c-b656-103f94f5b50b
Examining file 49/144: f3a5dad2-a101-4569-8dd1-867c41f76e9e
Examining file 50/144: ac165833-d5b6-4e03-8d41-d5b6a1078283
Examining file 51/144: 64b4cdba-8c43-4eab-b7cb-40fe563ae05b
Examining file 52/144: 2d94680c-f5f2-4181-a0b5-726286c8087b
Examining file 53/144: e02d7725-5383-4996-b6b4-d983a4654e3c
Examining file 54/144: 1f377f16-90b3-4861-b95b-1e6e9cbc64e0
Examining file 55/144: 783f0211-a484-4033-b2e5-a695701e4b98
Examining file 56/144: 2a600d5a-7e02-4c59-9a3e-06ba0cd26c33
Examining file 57/144: 52c0716a-2eac-4bb5-a574-9a5f54200382
Examining file 58/144: 4c744966-bc29-425f-99b9-836cb8f1440a
Examining file 59/144: c0812fea-f394-48d3-a9c4-c19c72d2dca5
Examining file 60/144: df9c631e-7216-4868-ba77-eda740df2bd0
Examining file 61/144: 74297073-b4b2-488d-a048-fdfdfcbd2949
Examining file 62/144: e497cd41-c3c5-4675-b812-ec862578a100
Examining file 63/144: 5751dc9a-a2b8-4758-8eed-e18a80941f49
Examining file 64/144: 22955fab-3544-44e7-b5c9-35965a56613e
Examining file 65/144: ed5ff8c6-7887-4bd7-9c0b-36b28db56f62
Examining file 66/144: b3a349a4-c320-4bc8-b4ec-8a4927244397
Examining file 67/144: 443c4c82-b729-49b5-9c41-00e8e721307b
Examining file 68/144: f2e2b443-039e-49ac-8648-184237c67cd9
Examining file 69/144: f88a3134-5a9e-4a69-b74f-70985d289468
Examining file 70/144: 3c9780b6-e80b-4d44-9a3d-04cdda910900
Examining file 71/144: 424259c6-8b56-4030-b6da-0ac519429179
Examining file 72/144: 552dba1f-8bb0-4970-ad9f-cb837ea0fba2
Examining file 73/144: 80f51999-f281-4563-8927-b1557c4a3a57
Examining file 74/144: a3732e26-9774-4662-b942-3bac4c21d518
Examining file 75/144: b9d8ce70-a02a-41ff-ac48-b6672ba37a19
Examining file 76/144: 7ff7b6c7-7c27-4789-8bbf-e1543c85c40d
Examining file 77/144: 10a3c193-2d08-46ac-8770-5026082cf1a8
Examining file 78/144: 389ee3f2-bd09-4a64-9bba-8ffa26fae28b
Examining file 79/144: a67340e7-c1d8-4776-a8c2-8d8950f9eaf3
Examining file 80/144: 11a6decc-e963-4f6c-bbe3-2c9954bd1e93
Examining file 81/144: 7fc7f1fb-a00f-4911-b1eb-8356d181370b
Examining file 82/144: 47a7cbb4-23ec-443c-89e8-bc14caf72907
Examining file 83/144: 6cac609b-b896-44a7-9b73-aaa3ae39e2fe
Examining file 84/144: 997bc7c3-31df-4915-ae44-8756d1e727af
Examining file 85/144: da8f564a-bb05-4121-ace8-c263617c2c45
Examining file 86/144: d02a5ff9-6b2a-4abe-b955-e31f81d5f160
Examining file 87/144: ee93f2f9-db91-411f-b02b-d8964964bbf5
Examining file 88/144: 7e64ca4b-dbaf-413a-a112-0801844c6c68
Examining file 89/144: 3295026c-61f6-446a-b476-f8603e0dc0bd
Examining file 90/144: 65d66096-02d6-4ced-b6a2-8e6cdc86a63f
Examining file 91/144: 8c9dae78-6e3d-47ec-9c7f-eda512f7cc3e
Examining file 92/144: 67a81078-fa31-4b23-962d-4adff1586ed5
Examining file 93/144: 8cf7a77d-65a4-4c40-af53-bd8324e5bb4b
Examining file 94/144: 148cf3c6-3d8e-4b13-9fb4-2f12a9eaa63b
Examining file 95/144: ed10080c-7243-40e5-9d40-06b9781d6a1f
Examining file 96/144: 60fa6085-d4b8-4030-99c7-b7a54d20b622
Examining file 97/144: 7ccf0c23-56bf-4d91-93bd-78011750eb8e
Examining file 98/144: d207a224-7de2-4174-a61f-75d501d04b1c
Examining file 99/144: 1523d05d-cd80-479e-ab97-030f01912b3c
Examining file 100/144: e88f074f-ac8a-4108-9c59-f17f4cc4f16d
Examining file 101/144: a736e1f4-f8a8-45a4-a756-46377650b356
Examining file 102/144: 5a672039-0f5f-43e8-8bee-98b90fa505c8
Examining file 103/144: 6a21eabf-3d18-409c-b768-82d585628dc5
Examining file 104/144: ed6123df-9c36-436d-b7c2-d0476c0ef83b
Examining file 105/144: 3d1e1b7d-61ee-48b1-984d-fcf3f3e781c6
Examining file 106/144: 120fc0fd-5aa0-4708-89e2-fbe50123a280
Examining file 107/144: 4ca8587f-8e16-4a5b-a1d3-5fd4baa44a7c
Examining file 108/144: f210e0f2-c437-4f7c-b6fe-a34ad5fafc62
Examining file 109/144: 2fbd5350-3660-4f4d-8a0c-064eb4a0731a
Examining file 110/144: 544903e1-dffe-47ff-9a58-8fb9f31a2ac3
Examining file 111/144: 31ecbf10-3ec2-4423-a440-779ad7c91fd9
Examining file 112/144: 4fa79b1e-80bc-463b-9986-28aec7ee5144
Examining file 113/144: a1fa26ea-faad-4664-978a-910d148eb699
Examining file 114/144: b51d361e-914c-42a2-84f3-d73adba25e42
Examining file 115/144: c90a489b-295a-4c6b-9d03-55d348c0660e
Examining file 116/144: 28be4bfd-3111-4339-982b-ce47128ec2f2
Examining file 117/144: 8f859387-5b18-44bf-b260-fb390e93afe5
Examining file 118/144: c54f5954-451b-4378-9a6f-60974e0ad9ed
Examining file 119/144: a77a6de5-8697-46f4-a23a-aee4c3ff7075
Examining file 120/144: 89a0e627-b431-434f-a41e-ee7e653ba5b8
Examining file 121/144: 6507d27f-8e2a-4bd0-86e2-e0bea2bdc190
Examining file 122/144: 0c8b2731-6985-47c3-92b4-b7edd8f9459d
Examining file 123/144: 2a972215-acc5-4dd3-b947-31ca61e3274e
Examining file 124/144: 7277f79b-c2c2-4838-9a6a-44247b290e59
Examining file 125/144: c0599912-3c84-47cb-992b-e4ff69cdcb9b
Examining file 126/144: 2527fc8f-f64d-4d42-ad14-6cf607b60196
Examining file 127/144: de6d4dc8-642a-4fb4-9e1a-9994be90ff80
Examining file 128/144: be1946c8-26fc-4d7f-9b09-e96d0d19a31a
Examining file 129/144: 3079ba26-d2ea-4188-b731-6965052fb884
Examining file 130/144: e5d0d15f-0b79-4a2c-9f4a-e96f20263b41
Examining file 131/144: 24e01abe-ce0e-4d4c-b9fa-1cb9705dea0f
Examining file 132/144: c284c3e7-07bf-4948-9092-65a02a4ee833
Examining file 133/144: 743b5d86-2672-4206-ac2a-adcb0c791811
Examining file 134/144: 430aa80f-890d-4702-98a2-8e7df250f550
Examining file 135/144: 85f8e332-23d3-4e76-9ce2-fb68386b65c4
Examining file 136/144: 5d0c3373-6112-4a34-b373-f34cd05f1475

Examining file 137/144: 50abc53a-e239-42fd-9dc7-16394d31c579
Examining file 138/144: 4e84bcf0-e0c4-4d18-92f8-d77db4593403
Examining file 139/144: ad6aeb66-6253-4881-940e-06e62c25ebf9
Examining file 140/144: fa152afc-97f0-4903-a0c1-36540101ab37
Examining file 141/144: 3120ec6f-b3d7-42ef-904b-e90deccf8025
Examining file 142/144: 74567b97-79f3-4b57-956c-501b48d9b3f3
Examining file 143/144: e8ac0c33-4057-4f58-9642-bfb47d91993b
Examining file 144/144: 29007b2e-57aa-4f01-a673-5369c2df09a3

In [9]:
# convert table to pandas dataframe
if nwb_type == "ephys":
    dandiset_files = pd.DataFrame(nwb_table, columns=("identifier", "size", "path", "session_time", "sub_name", "sub_sex", "sub_age", "sub_genotype", "probes", "stim types", "#_units", "session_length"))
else:
    dandiset_files = pd.DataFrame(nwb_table, columns=("identifier", "size", "path", "session_time", "sub_name", "session_id", "experiment_id", "container_id", "group", "group_count", "imaging_depth", "location", "fov_height", "fov_width", "specimen_name", "sub_sex", "sub_age", "sub_genotype", "stim_types", "#_rois", "session_end"))
dandiset_files

,identifier,size,path,session_time,sub_name,session_id,experiment_id,container_id,group,group_count,...,location,fov_height,fov_width,specimen_name,sub_sex,sub_age,sub_genotype,stim_types,#_rois,session_end
0,3a99f387-2af0-4ead-9af2-b3fb6319e966,1729071576,sub-770196/sub-770196_ses-multiplane-ophys-770...,2025-03-19 14:16:39.177500-07:00,770196,None,None,None,None,None,...,Structure: VISal Depth: 161,None,None,770196,F,P167D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,active_single_exemplar,None,3917.756320
1,7c7f7ac5-3252-42c2-8172-db7d8cea3a4b,980469748,sub-770962/sub-770962_ses-multiplane-ophys-770...,2025-03-08 11:22:47.102736-08:00,770962,None,None,None,None,None,...,Structure: VISal Depth: 161,None,None,770962,M,P152D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,active_shifting_exemplars,None,3920.138760
2,6d082069-8960-4bf2-9bec-2c0e0d6c9d5f,1545544760,sub-766757/sub-766757_ses-multiplane-ophys-766...,2025-02-19 14:31:09.098968-08:00,766757,None,None,None,None,None,...,Structure: VISal Depth: 148,None,None,766757,M,P156D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,passive,None,3502.008335
3,004043f9-321e-445e-b695-85e04002f2f1,1535386552,sub-766757/sub-766757_ses-multiplane-ophys-766...,2025-02-21 11:52:07.454331-08:00,766757,None,None,None,None,None,...,Structure: VISal Depth: 144,None,None,766757,M,P158D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,passive,None,3495.192990
4,9db56b96-0a4a-4bb3-be7e-2fced9efd393,1671603180,sub-766757/sub-766757_ses-multiplane-ophys-766...,2025-02-17 09:51:19.800644-08:00,766757,None,None,None,None,None,...,Structure: VISal Depth: 140,None,None,766757,M,P154D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,active_shifting_exemplars,None,3918.313840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,fa152afc-97f0-4903-a0c1-36540101ab37,1598986452,sub-770196/sub-770196_ses-multiplane-ophys-770...,2025-03-21 14:14:24.910581-07:00,770196,None,None,None,None,None,...,Structure: VISal Depth: 158,None,None,770196,F,P169D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,active_single_exemplar,None,3920.496550
140,3120ec6f-b3d7-42ef-904b-e90deccf8025,1960065116,sub-766757/sub-766757_ses-multiplane-ophys-766...,2025-02-05 14:14:02.646070-08:00,766757,None,None,None,None,None,...,Structure: VISal Depth: 144,None,None,766757,M,P142D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,active_single_exemplar,None,3916.145170
141,74567b97-79f3-4b57-956c-501b48d9b3f3,1344031012,sub-762551/sub-762551_ses-multiplane-ophys-762...,2025-01-27 10:07:52.846287-08:00,762551,None,None,None,None,None,...,Structure: VISal Depth: 142,None,None,762551,F,P155D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,active_shifting_exemplars,None,3919.738360
142,e8ac0c33-4057-4f58-9642-bfb47d91993b,1393133956,sub-762551/sub-762551_ses-multiplane-ophys-762...,2025-01-23 15:07:09.374731-08:00,762551,None,None,None,None,None,...,Structure: VISal Depth: 140,None,None,762551,F,P151D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,active_shifting_exemplars,None,3928.410900
143,29007b2e-57aa-4f01-a673-5369c2df09a3,1148788024,sub-762551/sub-762551_ses-multiplane-ophys-762...,2025-01-30 11:23:54.975176-08:00,762551,None,None,None,None,None,...,Structure: VISal Depth: 136,None,None,762551,F,P158D,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai93(TITL-G...,passive,None,3499.208880

In [10]:
if nwb_type == "ephys":
    m_count = len(dandiset_files["sub_sex"][dandiset_files["sub_sex"] == "M"])
    f_count = len(dandiset_files["sub_sex"][dandiset_files["sub_sex"] == "F"])
    sst_count = len(dandiset_files[dandiset_files["sub_genotype"].str.count("Sst") >= 1])
    pval_count = len(dandiset_files[dandiset_files["sub_genotype"].str.count("Pval") >= 1])
    wt_count = len(dandiset_files[dandiset_files["sub_genotype"].str.count("wt/wt") >= 1])
    print("Dandiset Overview:")
    print(len(dandiset_files), "dandiset_files")
    print(len(set(dandiset_files["sub_name"])), "subjects", m_count, "males,", f_count, "females")
    print(sst_count, "sst,", pval_count, "pval,", wt_count, "wt")
else:
    n_sessions = len(dandiset_files["session_id"].value_counts())
    subjects_info = dandiset_files.groupby(["sub_name", "sub_sex"]).size().reset_index().to_dict()
    m_count = len([sex for sex in subjects_info["sub_sex"].values() if sex == "M"])
    f_count = len([sex for sex in subjects_info["sub_sex"].values() if sex == "F"])
    print("Dandiset Overview:")
    print(len(dandiset_files), "dandiset_files")
    print(len(subjects_info["sub_name"]), "subjects", m_count, "males", f_count,"females")

Dandiset Overview:
144 dandiset_files
15 subjects 9 males 6 females

In [12]:
# output all session metadata to local CSV file
dandiset_files.to_csv("../../data/texture_sessions.csv")

### Selecting Files
**Pandas** syntax can be used to filter the table above and select individual sessions.

In [12]:
selected_files = dandiset_files[dandiset_files["size"] <= 2_500_000_000]
# selected_files = dandiset_files[dandiset_files["sub_sex"] == "F"]
# selected_files = dandiset_files[dandiset_files["#_units"] > 2900]
selected_files

,identifier,size,path,session_time,sub_name,sub_sex,sub_age,sub_genotype,probes,stim types,#_units,session_length
4,0073a783-5b41-42a8-882a-2960554d4e43,2108745405,sub-631570/sub-631570_ses-1194857009_ogen.nwb,2022-07-28 00:00:00-07:00,631570,F,92.0,Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,"{probeC, probeB, probeE, probeA, probeD, probe...","{spontaneous_presentations, ICwcfg1_presentati...",1789,7278.92195
7,f1a26076-0a3e-43c8-b138-5320bca7a23f,2469141920,sub-619296/sub-619296_ses-1187930705_ogen.nwb,2022-06-29 00:00:00-07:00,619296,M,154.0,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,"{probeC, probeB, probeE, probeA, probeD, probe...","{spontaneous_presentations, ICwcfg1_presentati...",1918,7278.13709
10,e61edcf3-26e9-44e1-9017-3ee558197da5,2453451408,sub-619293/sub-619293_ses-1184980079_ogen.nwb,2022-06-16 00:00:00-07:00,619293,M,141.0,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,"{probeC, probeB, probeE, probeA, probeD, probe...","{spontaneous_presentations, ICwcfg1_presentati...",2136,7454.53444

### Downloading Selected Files
To download the files, we use the same method that is explained in [Downloading an NWB File](./download_nwb.ipynb). This can be used with the paths from the selected sessions above to just download the files of interest.  Set `download_loc` to be the relative path of where the files should be downloaded. Note that if the files are large, this can take a long time.

In [13]:
download_loc = "."

In [14]:
selected_paths = set(selected_files.path)
selected_paths

{'sub-619293/sub-619293_ses-1184980079_ogen.nwb',
 'sub-619296/sub-619296_ses-1187930705_ogen.nwb',
 'sub-631570/sub-631570_ses-1194857009_ogen.nwb'}

In [15]:
for dandi_filepath in selected_paths:
    filename = dandi_filepath.split("/")[-1]
    file = my_dandiset.get_asset_by_path(dandi_filepath)
    file.download(f"{download_loc}/{filename}")
    print(f"Downloaded file to {download_loc}/{filename}")

Downloaded file to ./sub-631570_ses-1194857009_ogen.nwb
Downloaded file to ./sub-619293_ses-1184980079_ogen.nwb
Downloaded file to ./sub-631570_ses-1194857009_ogen.nwb
Downloaded file to ./sub-619296_ses-1187930705_ogen.nwb